spring.application.name=bonafide-system-backend
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-red-scene-aydgbcko-pooler.c-5.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_CH5lwikZT8Wg&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CH5lwikZT8Wg
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Propertiess
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP_WITH_TIMEZONE

# JWT Configuration
app.jwt.secret=6gpEI3BPwcEJUM0BqkeCYzkRNGBwxgLJoCueJE7VSz2
app.jwt.expiration-ms=86400000
app.jwt.issuer = "bonafide-api"

# Application Frontend Base URL
app.frontend.url=http://localhost:5173

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sairaj0608@gmail.com
spring.mail.password=clli szld hdie pnan
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
